name: Lints
on:
  pull_request:
    branches: ["master"]
    paths-ignore: ["docs/**", "README.md", "LICENSE"]
  push:
    branches: ["master"]
    paths-ignore: ["docs/**", "README.md", "LICENSE"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code Repository
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        cache-dependency-glob: uv.lock
    - name: Set up Python
      run: uv python install
    - name: Create venv, install dependencies
      run: |
        uv sync --group=lint --frozen
        source .venv/bin/activate
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
    - name: Lint
      run: |
        uv run ruff check
        uv run mypy src
